apiVersion: v1
 # The type of workload we are creating 
kind: Service
metadata:
# Name of Service - Required
  name: test-svc
# Specific details about the Service
spec:
# Type of Service to be deployed
  type: NodePort
  ports:
  - protocol: TCP
  - port: 80
  - targetport: 80
  - nodePort: 30080
  # Used to tell the Service which Pods to associate with
  selector:
    app: aks-web-app
